//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspSoundAnalisysSegment
    {
        [Key]
        public int SoundSegmentId { get; set; }
        public string VideoId { get; set; }
        public Nullable<int> SoundSegmentIndex { get; set; }
        public Nullable<double> Offset { get; set; }
        public Nullable<double> Duration { get; set; }
        public Nullable<double> TemperVal { get; set; }
        public string TemperMode { get; set; }
        public Nullable<double> ValenceVal { get; set; }
        public string ValenceMode { get; set; }
        public Nullable<double> ArousalVal { get; set; }
        public string ArousalMode { get; set; }
        public string Gender { get; set; }
        public string MoodPrimary { get; set; }
        public string MoodSecondary { get; set; }
        public string CompositePrimary { get; set; }
        public string CompositeSecondary { get; set; }
    
        public virtual AspVideoDetail AspVideoDetail { get; set; }
    }
}
