//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspVideoAnalysisSegments
    {
        public int VideoSegmentId { get; set; }
        public string VideoId { get; set; }
        public Nullable<int> VideoSegmentIndex { get; set; }
        public Nullable<double> Anger { get; set; }
        public Nullable<double> Contempt { get; set; }
        public Nullable<double> Disgust { get; set; }
        public Nullable<double> Fear { get; set; }
        public Nullable<double> Happiness { get; set; }
        public Nullable<double> Neutral { get; set; }
        public Nullable<double> Sadness { get; set; }
        public Nullable<double> Surprise { get; set; }
    
        public virtual AspVideoDetails AspVideoDetail { get; set; }
    }
}
