//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspVideoDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspVideoDetails()
        {
            this.AspSoundAnalisysSegments = new HashSet<AspSoundAnalisysSegments>();
            this.AspTextAnalisysSegments = new HashSet<AspTextAnalisysSegments>();
            this.AspVideoAnalysisSegments = new HashSet<AspVideoAnalysisSegments>();
        }
    
        public string VideoId { get; set; }
        public string VideoTitle { get; set; }
        public string ChannelId { get; set; }
        public string ChannelTitle { get; set; }
        public Nullable<System.DateTime> PublishedAt { get; set; }
        public string UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspSoundAnalisysSegments> AspSoundAnalisysSegments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspTextAnalisysSegments> AspTextAnalisysSegments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspVideoAnalysisSegments> AspVideoAnalysisSegments { get; set; }
    }
}
